# Generated by Django 5.2.8 on 2025-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
