# Generated by Django 5.2.8 on 2025-11-25 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="categories",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="server",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
